### PR TITLE
Create quick-start-electron-prebuilt.md

### PR DESCRIPTION
**Pull request by MikalDev**
Instructions on how to run the electron demo using prebuilt Greenworks binaries.

### CODE REVIEW

**Comment by hokein** [comment]
Thanks for making it happened! I think it is useful to have this doc for newbies.

The doc has a lot of duplications of https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md. The only difference is whether to download the prebuilt binaries or to build Greenworks.

Could we modify the existing build-instructions-electron.md to include the prebuilt-version step rather than creating a variant?

**Comment by MikalDev** [comment]
I definitely agree this is just a variant of an existing document. However, I don't think it's a good idea to add it to build instructions as an alternative set up of steps - because it will be confusing for the users this document is targeting - the newbies. I think it's good if they just have one document and one set of steps to follow to get started.

**Comment by hokein** [comment]
Introducing duplicated content will add maintenance burden (it easily gets out of sync). 

Regarding the content of newly-create document: I'm not sure using&modifying electron's quick start example is a good idea -- if the example is changed, our instructions maybe out of date. Since We already have an electron example in Greenworks repo, can we use it?

**Comment by MikalDev** [comment]
Ok, I understand, moved the appropriate section to the electron build instructions instead.

**Pull request closed without merging**
