### PR TITLE
Add APIs for decrypting ticket

### LINKED ISSUE #93: Encrypted tickets decrypting support
We're working on nodejs-based server for an online game, and now looking into possible solutions for creating Steam integration. We'd like to make use of Encrypted Application Tickets to avoid connecting to Steam servers each time a user tries to authenticate with his SteamID. As far as I can tell the following APIs are missing in greenworks:

`SteamEncryptedAppTicket_BDecryptTicket`
`SteamEncryptedAppTicket_BIsTicketForApp()`
`SteamEncryptedAppTicket_GetTicketIssueTime()`
`SteamEncryptedAppTicket_GetTicketSteamID`

Any chance they will be added soon?

### PR DESCRIPTION
**Pull request by hokein**
Fixes #93.

@jahrain : I also made some changes in `getAuthSessionTicket` and `get getEncryptedAppTicket`, Now the `Ticket` is returned as a `node::Buffer` instead of a hex-hardcoded `String`.
 
cc @artch

### CODE REVIEW

**Comment by hokein** [comment]
A bad news updated:

These decryption APIs don't work due to missing symbols from steam's distributed dynamic binary (`libsteam_api.dylib`, `libsteam_api.so`). When calling these APIs from node.js, stack trace is like:

```
node: symbol lookup error: /XX/lib/greenworks-linux64.node: undefined symbol: SteamEncryptedAppTicket_BDecryptTicket
```

Looks like the dynamic library doesn't expose `SteamEncryptedAppTicket_BDecryptTicket`
`SteamEncryptedAppTicket_BIsTicketForApp`, `SteamEncryptedAppTicket_GetTicketIssueTime` and `SteamEncryptedAppTicket_GetTicketSteamID` symbols (at least on OSX and Linux): 

```
> nm -gC lib/libsteam_api.so | grep Ticket
000000000001e4fc T CEncryptedAppTicketResponse_t_RemoveCallResult
000000000001e45d T CEncryptedAppTicketResponse_t_SetCallResult
000000000001c470 T SteamAPI_ISteamGameServer_CancelAuthTicket
000000000001c44c T SteamAPI_ISteamGameServer_GetAuthSessionTicket
000000000001aadb T SteamAPI_ISteamUser_CancelAuthTicket
000000000001aac0 T SteamAPI_ISteamUser_GetAuthSessionTicket
000000000001ab1a T SteamAPI_ISteamUser_GetEncryptedAppTicket
000000000001ab0e T SteamAPI_ISteamUser_RequestEncryptedAppTicket
```

I'm afraid we could do nothing for the issue except consulting guys from Steam. Unfortunately I have no permission to access the [`Steamworks Dev group`](http://steamcommunity.com/groups/steamworks/discussions) right now. (Only guys who have published a game on Steam or their games gets greenlight can get the permission) :(

@patrickklug Is it possible to add me to list like `Game Dev Tycoon` maker list in Steam? So that I can access that that group?

**Comment by artch** [comment]
I noticed there are other library files in the `sdk/public/steam/lib` folder:
```
sdk/public/steam/lib/linux32/libsdkencryptedappticket.so
sdk/public/steam/lib/osx32/libsdkencryptedappticket.dylib
sdk/public/steam/lib/win32/sdkencryptedappticket64.dll
```

Looks like these APIs are exposed in their own separate files, so that they should be (optionally) included in the redistributable libs package.

**Comment by MadSpyxFR** [comment]
@artch Sadly you can't use only the encryptedappticket library alone (and the library is requiered for client and server)

**Comment by artch** [comment]
OK then, it should not be an issue, we can include both libraries.

**Comment by hokein** [comment]
@artch 
Oh, exactly! The libraries in `sdk/public/steam/lib` are what we need. I totally missed the libraries there. Thanks for the hint!

**Comment by hokein** [comment]
@artch 
The PR should work now. I tested with Steamwork sample Spacewar, and everything worked. You can fetch this branch and test it on your sever :-)

**Comment by artch** [comment]
Tested on our setup, works like a charm, thank you!

**Comment by hokein** [comment]
@artch Great, Thanks for testing. I merge it now.

**Comment by hokein** [comment]
@artch btw, do you use `greenworks` in your game? If so, could you add your game to our  [`app-games`](https://github.com/greenheartgames/greenworks/wiki/Apps-games-using-greenworks) page? Thanks.

**Comment by artch** [comment]
@hokein Sure, added!

**Comment by artch** [comment]
When do you plan to include this commit into prebuilt binaries?

**Comment by hokein** [comment]
@artch I would expect to release a new version after electron upgrades to Chrome 54, which are currently in progress. But I don't know the exact timeline.

**Pull request merged**
