### PR TITLE
Add AppID to PublishWorkshopFile function

### PR DESCRIPTION
**Pull request by MadSpyxFR**
1st commits, build tested, not tested in live app/game atm

### CODE REVIEW

**Comment by hokein** [comment]
@MadSpyxFR  Thanks for you contributions! A few idea below.

I think we should also add `APPID` to these apis:

* `greeenworks.ugcPublish`
* `greenworks.publishWorkshopFile`
* `greenworks.ugcGetItems`
* `greenworks.ugcGetUserItems`
* `greenworks.ugcSynchronizeItems`

On the design aspect, we can add an option `AppID` as the first function argument, so that we won't break backward compatibility which providing new features,  the new APIs look like:

* `greenworks.ugcPublish([AppID, ] file_path, title, description, image_path, success_callback, [error_callback], [progress_callback])`
* `greenworks.publishWorkshopFile([AppID, ] file_path, image_path, title, description, success_callback, [error_callback]))`
* `greenworks.ugcGetItems([AppID, ] ugc_matching_type, ugc_query_type, success_callback, [error_callback])`
* `greenworks.ugcGetUserItems([AppID, ]ugc_matching_type, ugc_list_sort_order, ugc_list, success_callback, [error_callback])`
* `greenworks.ugcSynchronizeItems([AppID, ] sync_dir, success_callback, [error_callback]`

For the implementation, I'd move the arguments' handling code from C++ to JavaScript, which will keep C++ code simpler and take benefits from JavaScript. Take `greenworks.ugcGetItems` for example:

* In C++: we still implement a `_ugcGetItems` API which accepts required arguments `AppID`, `ugc_matching_type`, `ugc_query_type`, `success_callback` and the optional `error_callback`.
* In JavaScript: we create a wrapper `ugcGetItems` using the internal `_ugcGetItems`, basically the code like:

```js
greenworks.ugcGetItem = function (appid, ugc_matching_type, ugc_list_sort_order, ugc_list, success_callback, error_callback) {
     if (typeof appid !== 'number') {
       error_callback = success_callback
       success_callback = ugc_list
       ugc_list = ugc_list_sort_order
       ugc_list_sort_order = ugc_matching_type
       ugc_matching_type = appid
       appid = greenworks.getAppId();
    }
    
    greenworks._ugcGetItem(appid, ...)
}
```

Also for C++ code, please follow the [Google C++ code style](https://google.github.io/styleguide/cppguide.html) :)

**Comment by MadSpyxFR** [comment]
I would like to say instead of using  the deprecated ISteamRemoteStorage-based Workshop implementation, we could use the workshop based on full ISteamUGC API (createitem/startupdateitem) ?

**Comment by hokein** [comment]
@MadSpyxFR 
Oops, I totally missed your reply. Sorry for the delay.

> I would like to say instead of using the deprecated ISteamRemoteStorage-based Workshop implementation, we could use the workshop based on full ISteamUGC API (createitem/startupdateitem) ?

No objection with this. We still need to keep and maintain the old implementations for the backward compatibility.

**Comment by Misto423** [comment]
Hey,  I finally got around to testing this a bit.  I did run into some issues and it may seem like some other things might be breaking after trying to use the app id. 

First I did have to update the greenworks.js file (as mentioned above) since I was using greenworks.ugcPublish.  

Once I had those changes, the publish would report a success by calling the success callback, but would return with a "Error on reading files" message.  I couldn't figure out exactly why adding the app id would cause errors with these files but there may be some more changes needed to fully support this.

**Comment by hokein** [comment]
@Misto423 Thanks for the reply.
I haven't tried it yet, so I can't provide more further comments on it.

Looks like you make some changes on these APIs (adding app_id), would you mind sending a PR about it, so that we can discuss. Thanks.

@MadSpyxFR I apologies that my prior comment would make the change larger than we originally expected, which may require more your valuable time. But I think it's worth the effort. If you are busy with other stuff, I'm happy to take it.

For using ISteamUGC based APIs, I 👍  on it, it would be nice to provide these APIs in Greenworks, but this is not a high priority unless more users are requiring them. Again thanks for your contributions.

**Comment by MadSpyxFR** [comment]
Closing this PR. I will open a new one soon

**Pull request closed without merging**
